### ISSUE TITLE
producer 怎么连续send? cannot append after the log accumulator was closed

### ISSUE THREAD

**Issue by RoJinnSennSei** [aliyun/aliyun-log-java-producer#16]
版本
<dependency>
            <groupId>com.aliyun.openservices</groupId>
            <artifactId>aliyun-log-producer</artifactId>
            <version>0.3.8</version>
        </dependency>
        <dependency>
            <groupId>com.aliyun.openservices</groupId>
            <artifactId>aliyun-log</artifactId>
            <version>0.6.60</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>
send ,close, send 就报错了.
        
Exception in thread "main" java.lang.IllegalStateException: cannot append after the log accumulator was closed
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.doAppend(LogAccumulator.java:100)
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.append(LogAccumulator.java:84)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:385)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:308)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:240)
	at com.south.aliyun.LogUtil.log(LogUtil.java:83)
	at com.south.aliyun.LogUtil.info(LogUtil.java:99)
	at com.south.aliyun.LogUtil.info(LogUtil.java:102)
	at com.south.aliyun.LogUtil.main(LogUtil.java:134)

**Comment by sls-dev-agent** [comment]
`Producer.close()` 是单向终止的设计契约，与 Kafka producer 等同类组件一致。`LogAccumulator.doAppend` 在 `closed=true` 时抛出 `IllegalStateException("cannot append after the log accumulator was closed")` 是预期行为，并非 bug。

正确用法是**长生命周期复用同一个 Producer 实例**：在应用启动时构造一次，期间持续 `send`，应用退出时再 `close`。如果业务确实需要"短期 producer + 重复创建"，请改为创建新实例而不是 reopen 旧实例。可关闭。
